package examples_test

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/masudur-rahman/styx/v2"
)

// Money is a caller's own type, mapped to a column type by RegisterSQLType.
type Money int64

func init() {
	styx.RegisterSQLType(reflect.TypeOf(Money(0)), map[string]string{
		styx.DialectPostgres: "NUMERIC(19,4)",
		styx.DialectSQLite:   "REAL",
	})
}

// Meta is stored as a single JSON column.
type Meta struct {
	Source string `json:"source"`
}

// Auditable is embedded below. Embedding flattens its fields into the outer
// table, so every table can share bookkeeping columns without repeating them.
type Auditable struct {
	CreatedAt time.Time  `db:"created_at"`
	CreatedBy string     `db:"created_by"`
	DeletedAt *time.Time `db:"deleted_at,archive"`
}

// Ledger uses every db tag styx understands. The column name comes before the
// comma; the options after it are separated by spaces, never commas.
type Ledger struct {
	// pk + autoincr: primary key, generated by the database.
	ID int64 `db:"id,pk autoincr"`

	// type=: names the column type outright. Portable names such as uuid map
	// per dialect; anything else is passed through as literal SQL.
	OwnerID string `db:"owner_id,type=uuid"`
	Ref     string `db:"ref,type=varchar(32)"`

	// styx.UUID reaches a native uuid column through its Go type, no tag.
	BatchID styx.UUID `db:"batch_id"`

	// Registered custom type.
	Amount Money `db:"amount"`

	// uq: single-column unique. notnull: NOT NULL.
	Code  string `db:"code,uq"`
	Title string `db:"title,notnull"`

	// uqs: every uqs field joins one composite UNIQUE(...).
	Tenant string `db:"tenant,uqs"`
	Period string `db:"period,uqs"`

	// req: always written, even when zero. Without it a zero value is skipped.
	Revision int `db:"revision,req"`

	// idx / uidx: single-column index. Add ":name" to combine fields into one
	// multi-column index.
	Status   string `db:"status,idx"`
	Email    string `db:"email,uidx"`
	Region   string `db:"region,idx:region_zone"`
	Zone     string `db:"zone,idx:region_zone"`
	Sequence int    `db:"sequence,uidx:tenant_seq"`

	// json: any struct, map or slice stored as a JSON column.
	Meta Meta `db:"meta,json"`

	// Empty column name: derived from the field name as snake_case.
	FullName string `db:",notnull"`

	// "-": never a column. Not written, read, or scanned.
	Scratch string `db:"-"`

	// archive and the audit columns arrive through the embed.
	Auditable
}

// Example_structTags exercises every db tag on one struct.
func Example_structTags() {
	db := openDB()
	if err := db.Sync(ctx, Ledger{}); err != nil {
		fmt.Println("sync failed:", err)
		return
	}

	l := &Ledger{
		OwnerID: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
		Ref:     "LDG-1",
		BatchID: "0b6dd39a-2f83-4a30-9f3c-2f4d0f0a1b2c",
		Amount:  1999,
		Code:    "AC-1",
		Title:   "opening balance",
		Tenant:  "acme",
		Period:  "2026-08",
		Status:  "open",
		Email:   "ops@acme.test",
		Region:  "apac",
		Zone:    "a",
		Meta:    Meta{Source: "import"},

		FullName: "Acme Opening Balance",
		Scratch:  "never stored",
	}
	l.CreatedBy = "masud"
	l.CreatedAt = time.Date(2026, 8, 21, 9, 0, 0, 0, time.UTC)

	if _, err := db.Table("ledger").InsertOne(ctx, l); err != nil {
		fmt.Println("insert failed:", err)
		return
	}

	var got Ledger
	db.Table("ledger").ID(l.ID).FindOne(ctx, &got)

	fmt.Println("owner:", got.OwnerID)
	fmt.Println("batch:", got.BatchID)
	fmt.Println("amount:", got.Amount)
	fmt.Println("title:", got.Title)
	fmt.Println("meta source:", got.Meta.Source)
	fmt.Println("full name:", got.FullName)
	fmt.Println("created by:", got.CreatedBy)
	fmt.Println("scratch persisted:", got.Scratch != "")

	// req means Revision is written even at zero, so a second row with the
	// same tenant and period trips the composite unique constraint.
	_, err := db.Table("ledger").InsertOne(ctx, &Ledger{
		Code: "AC-2", Title: "dup", Tenant: "acme", Period: "2026-08",
	})
	fmt.Println("composite unique enforced:", err != nil)

	// notnull rejects a missing value.
	_, err = db.Table("ledger").InsertOne(ctx, &Ledger{Code: "AC-3"})
	fmt.Println("notnull enforced:", err != nil)

	// archive: DeleteOne marks the row instead of removing it.
	db.Table("ledger").ID(l.ID).DeleteOne(ctx)
	found, _ := db.Table("ledger").ID(l.ID).FindOne(ctx, &Ledger{})
	fmt.Println("found after delete:", found)

	// Output:
	// owner: 6ba7b810-9dad-11d1-80b4-00c04fd430c8
	// batch: 0b6dd39a-2f83-4a30-9f3c-2f4d0f0a1b2c
	// amount: 1999
	// title: opening balance
	// meta source: import
	// full name: Acme Opening Balance
	// created by: masud
	// scratch persisted: false
	// composite unique enforced: true
	// notnull enforced: true
	// found after delete: false
}

// ---------------------------------------------------------------------------
// Choosing a column type without a tag
// ---------------------------------------------------------------------------

// Patient uses styx.UUID, whose Go type alone selects a native uuid column.
// The tag carries only pk.
type Patient struct {
	ID   styx.UUID `db:"id,pk"`
	Name string    `db:"name"`
}

// Example_uuidColumn shows styx.UUID as a primary key. A plain string field
// reaches the same column type with `db:"id,pk type=uuid"` instead.
func Example_uuidColumn() {
	db := openDB()
	db.Sync(ctx, Patient{})

	p := &Patient{ID: "6ba7b810-9dad-11d1-80b4-00c04fd430c8", Name: "Ada"}
	db.Table("patient").InsertOne(ctx, p)

	var got Patient
	db.Table("patient").ID(p.ID).FindOne(ctx, &got)

	fmt.Println("id:", got.ID)
	fmt.Println("name:", got.Name)

	// Output:
	// id: 6ba7b810-9dad-11d1-80b4-00c04fd430c8
	// name: Ada
}

// CSV packs a string slice into one column. A type implementing sql.Scanner
// and driver.Valuer handles its own reading and writing, so it needs no tag.
type CSV []string

func (c *CSV) Scan(src any) error {
	s, ok := src.(string)
	if !ok || s == "" {
		*c = nil
		return nil
	}
	*c = strings.Split(s, ",")
	return nil
}

func (c CSV) Value() (driver.Value, error) { return strings.Join(c, ","), nil }

var _ sql.Scanner = (*CSV)(nil)

type TaggedPost struct {
	ID   int64  `db:"id,pk autoincr"`
	Name string `db:"name"`
	Tags CSV    `db:"tags"`
}

// Example_scannerColumn shows a column type implementing sql.Scanner.
func Example_scannerColumn() {
	db := openDB()
	db.Sync(ctx, TaggedPost{})

	p := &TaggedPost{Name: "styx", Tags: CSV{"go", "orm", "sql"}}
	db.Table("tagged_post").InsertOne(ctx, p)

	var got TaggedPost
	db.Table("tagged_post").ID(p.ID).FindOne(ctx, &got)

	fmt.Println("name:", got.Name)
	fmt.Println("tags:", got.Tags)

	// Output:
	// name: styx
	// tags: [go orm sql]
}

// ---------------------------------------------------------------------------
// Embedded structs
// ---------------------------------------------------------------------------

// Article embeds Auditable, so it gets created_at, created_by and deleted_at
// without repeating them. Tags are found through the embed too, so archive
// still drives soft delete.
type Article struct {
	ID    int64  `db:"id,pk autoincr"`
	Title string `db:"title"`
	Auditable
}

// Example_embeddedStruct shows an embedded struct flattened into columns.
func Example_embeddedStruct() {
	db := openDB()
	db.Sync(ctx, Article{})

	a := &Article{Title: "styx v2"}
	a.CreatedBy = "masud"
	a.CreatedAt = time.Date(2026, 8, 21, 9, 0, 0, 0, time.UTC)
	db.Table("article").InsertOne(ctx, a)

	var got Article
	db.Table("article").ID(a.ID).FindOne(ctx, &got)

	fmt.Println("title:", got.Title)
	fmt.Println("created by:", got.CreatedBy)
	fmt.Println("created at:", got.CreatedAt.Format("2006-01-02"))

	db.Table("article").ID(a.ID).DeleteOne(ctx)
	found, _ := db.Table("article").ID(a.ID).FindOne(ctx, &Article{})
	fmt.Println("found after delete:", found)

	// Output:
	// title: styx v2
	// created by: masud
	// created at: 2026-08-21
	// found after delete: false
}

// Timestamped shows shadowing: a field on the outer struct hides one of the
// same column name from the embed, matching Go's own rule.
type Timestamped struct {
	ID        int64  `db:"id,pk autoincr"`
	CreatedBy string `db:"created_by,notnull"`
	Auditable
}

// Example_embeddedShadowing shows an outer field overriding an embedded one.
func Example_embeddedShadowing() {
	db := openDB()
	db.Sync(ctx, Timestamped{})

	row := &Timestamped{CreatedBy: "outer"}
	db.Table("timestamped").InsertOne(ctx, row)

	var got Timestamped
	db.Table("timestamped").ID(row.ID).FindOne(ctx, &got)

	fmt.Println("created by:", got.CreatedBy)
	fmt.Println("embedded field is empty:", got.Auditable.CreatedBy == "")

	// Output:
	// created by: outer
	// embedded field is empty: true
}

// Relations are declared with their own tags. The column part is "-" because
// the field holds related entities rather than a column of this table.
type TagAuthor struct {
	ID    int64      `db:"id,pk autoincr"`
	Name  string     `db:"name"`
	Books []TagBook  `db:"-,o2m fk:author_id"`
	Tags  []TagLabel `db:"-,m2m join:author_labels fk:author_id ref:label_id"`
}

type TagBook struct {
	ID       int64      `db:"id,pk autoincr"`
	AuthorID int64      `db:"author_id"`
	Author   *TagAuthor `db:"-,m2o fk:author_id"`
}

type TagLabel struct {
	ID   int64  `db:"id,pk autoincr"`
	Name string `db:"name"`
}

// Example_relationTags lists the association tags. o2m and m2m sit on the
// parent, m2o on the child holding the foreign key.
func Example_relationTags() {
	for _, f := range []string{
		`Books []TagBook  ` + "`" + `db:"-,o2m fk:author_id"` + "`",
		`Author *TagAuthor ` + "`" + `db:"-,m2o fk:author_id"` + "`",
		`Tags  []TagLabel ` + "`" + `db:"-,m2m join:author_labels fk:author_id ref:label_id"` + "`",
	} {
		fmt.Println(f)
	}

	// Output:
	// Books []TagBook  `db:"-,o2m fk:author_id"`
	// Author *TagAuthor `db:"-,m2o fk:author_id"`
	// Tags  []TagLabel `db:"-,m2m join:author_labels fk:author_id ref:label_id"`
}

// BadTags misuses the tag two ways: attributes are separated by spaces, not
// commas, and uqq is not an option. Both used to be dropped in silence, so the
// table came out with no primary key and no unique constraint.
type BadTags struct {
	ID    int64  `db:"id,pk,uq"`
	Email string `db:"email,uqq"`
}

// Example_tagValidation shows Sync rejecting malformed db tags.
func Example_tagValidation() {
	db := openDB()

	err := db.Sync(ctx, BadTags{})
	msg := fmt.Sprint(err)

	fmt.Println("rejected:", err != nil)
	fmt.Println("names the comma:", strings.Contains(msg, "separated by spaces"))
	fmt.Println("names the typo:", strings.Contains(msg, `unknown option "UQQ"`))
	fmt.Println("reports both fields:",
		strings.Contains(msg, "field ID") && strings.Contains(msg, "field Email"))

	// Output:
	// rejected: true
	// names the comma: true
	// names the typo: true
	// reports both fields: true
}
