// Code generated by MockGen. DO NOT EDIT.
// Source: sql/database.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sql0 "github.com/masudur-rahman/styx/sql"
)

// MockEngine is a mock of Engine interface.
type MockEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEngineMockRecorder
}

// MockEngineMockRecorder is the mock recorder for MockEngine.
type MockEngineMockRecorder struct {
	mock *MockEngine
}

// NewMockEngine creates a new mock instance.
func NewMockEngine(ctrl *gomock.Controller) *MockEngine {
	mock := &MockEngine{ctrl: ctrl}
	mock.recorder = &MockEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngine) EXPECT() *MockEngineMockRecorder {
	return m.recorder
}

// AllCols mocks base method.
func (m *MockEngine) AllCols() sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllCols")
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// AllCols indicates an expected call of AllCols.
func (mr *MockEngineMockRecorder) AllCols() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllCols", reflect.TypeOf((*MockEngine)(nil).AllCols))
}

// Avg mocks base method.
func (m *MockEngine) Avg(col string, alias ...string) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{col}
	for _, a := range alias {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Avg", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Avg indicates an expected call of Avg.
func (mr *MockEngineMockRecorder) Avg(col interface{}, alias ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{col}, alias...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Avg", reflect.TypeOf((*MockEngine)(nil).Avg), varargs...)
}

// BeginTx mocks base method.
func (m *MockEngine) BeginTx(ctx context.Context) (sql0.Engine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(sql0.Engine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockEngineMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockEngine)(nil).BeginTx), ctx)
}

// Close mocks base method.
func (m *MockEngine) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEngineMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEngine)(nil).Close))
}

// Columns mocks base method.
func (m *MockEngine) Columns(cols ...string) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range cols {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Columns", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Columns indicates an expected call of Columns.
func (mr *MockEngineMockRecorder) Columns(cols ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Columns", reflect.TypeOf((*MockEngine)(nil).Columns), cols...)
}

// Commit mocks base method.
func (m *MockEngine) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockEngineMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockEngine)(nil).Commit))
}

// Count mocks base method.
func (m *MockEngine) Count(col string, alias ...string) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{col}
	for _, a := range alias {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Count", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Count indicates an expected call of Count.
func (mr *MockEngineMockRecorder) Count(col interface{}, alias ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{col}, alias...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockEngine)(nil).Count), varargs...)
}

// DeleteOne mocks base method.
func (m *MockEngine) DeleteOne(ctx context.Context, filter ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range filter {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteOne", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOne indicates an expected call of DeleteOne.
func (mr *MockEngineMockRecorder) DeleteOne(ctx interface{}, filter ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, filter...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*MockEngine)(nil).DeleteOne), varargs...)
}

// Distinct mocks base method.
func (m *MockEngine) Distinct() sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Distinct")
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Distinct indicates an expected call of Distinct.
func (mr *MockEngineMockRecorder) Distinct() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Distinct", reflect.TypeOf((*MockEngine)(nil).Distinct))
}

// DropTable mocks base method.
func (m *MockEngine) DropTable(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropTable", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DropTable indicates an expected call of DropTable.
func (mr *MockEngineMockRecorder) DropTable(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropTable", reflect.TypeOf((*MockEngine)(nil).DropTable), ctx, name)
}

// EnableValidation mocks base method.
func (m *MockEngine) EnableValidation(enable bool) sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableValidation", enable)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// EnableValidation indicates an expected call of EnableValidation.
func (mr *MockEngineMockRecorder) EnableValidation(enable interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableValidation", reflect.TypeOf((*MockEngine)(nil).EnableValidation), enable)
}

// Exec mocks base method.
func (m *MockEngine) Exec(ctx context.Context, query string, args ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockEngineMockRecorder) Exec(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockEngine)(nil).Exec), varargs...)
}

// Exists mocks base method.
func (m *MockEngine) Exists(subquery string, args ...any) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{subquery}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exists", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockEngineMockRecorder) Exists(subquery interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{subquery}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockEngine)(nil).Exists), varargs...)
}

// FindMany mocks base method.
func (m *MockEngine) FindMany(ctx context.Context, documents any, filter ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, documents}
	for _, a := range filter {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindMany", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindMany indicates an expected call of FindMany.
func (mr *MockEngineMockRecorder) FindMany(ctx, documents interface{}, filter ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, documents}, filter...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockEngine)(nil).FindMany), varargs...)
}

// FindOne mocks base method.
func (m *MockEngine) FindOne(ctx context.Context, document any, filter ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, document}
	for _, a := range filter {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockEngineMockRecorder) FindOne(ctx, document interface{}, filter ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, document}, filter...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockEngine)(nil).FindOne), varargs...)
}

// ForceDelete mocks base method.
func (m *MockEngine) ForceDelete(ctx context.Context, filter ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range filter {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ForceDelete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceDelete indicates an expected call of ForceDelete.
func (mr *MockEngineMockRecorder) ForceDelete(ctx interface{}, filter ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, filter...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceDelete", reflect.TypeOf((*MockEngine)(nil).ForceDelete), varargs...)
}

// GroupBy mocks base method.
func (m *MockEngine) GroupBy(cols ...string) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range cols {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GroupBy", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// GroupBy indicates an expected call of GroupBy.
func (mr *MockEngineMockRecorder) GroupBy(cols ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupBy", reflect.TypeOf((*MockEngine)(nil).GroupBy), cols...)
}

// Having mocks base method.
func (m *MockEngine) Having(cond string, args ...any) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{cond}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Having", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Having indicates an expected call of Having.
func (mr *MockEngineMockRecorder) Having(cond interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{cond}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Having", reflect.TypeOf((*MockEngine)(nil).Having), varargs...)
}

// ID mocks base method.
func (m *MockEngine) ID(id any) sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID", id)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockEngineMockRecorder) ID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockEngine)(nil).ID), id)
}

// In mocks base method.
func (m *MockEngine) In(col string, values ...any) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{col}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "In", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// In indicates an expected call of In.
func (mr *MockEngineMockRecorder) In(col interface{}, values ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{col}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "In", reflect.TypeOf((*MockEngine)(nil).In), varargs...)
}

// InnerJoin mocks base method.
func (m *MockEngine) InnerJoin(table, condition string) sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InnerJoin", table, condition)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// InnerJoin indicates an expected call of InnerJoin.
func (mr *MockEngineMockRecorder) InnerJoin(table, condition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InnerJoin", reflect.TypeOf((*MockEngine)(nil).InnerJoin), table, condition)
}

// InsertMany mocks base method.
func (m *MockEngine) InsertMany(ctx context.Context, documents []any) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMany", ctx, documents)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertMany indicates an expected call of InsertMany.
func (mr *MockEngineMockRecorder) InsertMany(ctx, documents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMany", reflect.TypeOf((*MockEngine)(nil).InsertMany), ctx, documents)
}

// InsertOne mocks base method.
func (m *MockEngine) InsertOne(ctx context.Context, document any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOne", ctx, document)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOne indicates an expected call of InsertOne.
func (mr *MockEngineMockRecorder) InsertOne(ctx, document interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockEngine)(nil).InsertOne), ctx, document)
}

// Join mocks base method.
func (m *MockEngine) Join(table, condition string) sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", table, condition)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockEngineMockRecorder) Join(table, condition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockEngine)(nil).Join), table, condition)
}

// LeftJoin mocks base method.
func (m *MockEngine) LeftJoin(table, condition string) sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeftJoin", table, condition)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// LeftJoin indicates an expected call of LeftJoin.
func (mr *MockEngineMockRecorder) LeftJoin(table, condition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeftJoin", reflect.TypeOf((*MockEngine)(nil).LeftJoin), table, condition)
}

// Like mocks base method.
func (m *MockEngine) Like(col, pattern string) sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", col, pattern)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Like indicates an expected call of Like.
func (mr *MockEngineMockRecorder) Like(col, pattern interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockEngine)(nil).Like), col, pattern)
}

// Limit mocks base method.
func (m *MockEngine) Limit(n int64) sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Limit", n)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Limit indicates an expected call of Limit.
func (mr *MockEngineMockRecorder) Limit(n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Limit", reflect.TypeOf((*MockEngine)(nil).Limit), n)
}

// Max mocks base method.
func (m *MockEngine) Max(col string, alias ...string) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{col}
	for _, a := range alias {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Max", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Max indicates an expected call of Max.
func (mr *MockEngineMockRecorder) Max(col interface{}, alias ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{col}, alias...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Max", reflect.TypeOf((*MockEngine)(nil).Max), varargs...)
}

// Min mocks base method.
func (m *MockEngine) Min(col string, alias ...string) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{col}
	for _, a := range alias {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Min", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Min indicates an expected call of Min.
func (mr *MockEngineMockRecorder) Min(col interface{}, alias ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{col}, alias...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Min", reflect.TypeOf((*MockEngine)(nil).Min), varargs...)
}

// MustCols mocks base method.
func (m *MockEngine) MustCols(cols ...string) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range cols {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MustCols", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// MustCols indicates an expected call of MustCols.
func (mr *MockEngineMockRecorder) MustCols(cols ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustCols", reflect.TypeOf((*MockEngine)(nil).MustCols), cols...)
}

// MustFilterCols mocks base method.
func (m *MockEngine) MustFilterCols(cols ...string) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range cols {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MustFilterCols", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// MustFilterCols indicates an expected call of MustFilterCols.
func (mr *MockEngineMockRecorder) MustFilterCols(cols ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustFilterCols", reflect.TypeOf((*MockEngine)(nil).MustFilterCols), cols...)
}

// NotExists mocks base method.
func (m *MockEngine) NotExists(subquery string, args ...any) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{subquery}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NotExists", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// NotExists indicates an expected call of NotExists.
func (mr *MockEngineMockRecorder) NotExists(subquery interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{subquery}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotExists", reflect.TypeOf((*MockEngine)(nil).NotExists), varargs...)
}

// NotLike mocks base method.
func (m *MockEngine) NotLike(col, pattern string) sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotLike", col, pattern)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// NotLike indicates an expected call of NotLike.
func (mr *MockEngineMockRecorder) NotLike(col, pattern interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotLike", reflect.TypeOf((*MockEngine)(nil).NotLike), col, pattern)
}

// Offset mocks base method.
func (m *MockEngine) Offset(n int64) sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Offset", n)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Offset indicates an expected call of Offset.
func (mr *MockEngineMockRecorder) Offset(n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Offset", reflect.TypeOf((*MockEngine)(nil).Offset), n)
}

// Or mocks base method.
func (m *MockEngine) Or(cond string, args ...any) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{cond}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Or", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Or indicates an expected call of Or.
func (mr *MockEngineMockRecorder) Or(cond interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{cond}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Or", reflect.TypeOf((*MockEngine)(nil).Or), varargs...)
}

// OrderBy mocks base method.
func (m *MockEngine) OrderBy(col string, direction ...string) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{col}
	for _, a := range direction {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OrderBy", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// OrderBy indicates an expected call of OrderBy.
func (mr *MockEngineMockRecorder) OrderBy(col interface{}, direction ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{col}, direction...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderBy", reflect.TypeOf((*MockEngine)(nil).OrderBy), varargs...)
}

// Paginate mocks base method.
func (m *MockEngine) Paginate(page, perPage int64) sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Paginate", page, perPage)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Paginate indicates an expected call of Paginate.
func (mr *MockEngineMockRecorder) Paginate(page, perPage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paginate", reflect.TypeOf((*MockEngine)(nil).Paginate), page, perPage)
}

// Query mocks base method.
func (m *MockEngine) Query(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockEngineMockRecorder) Query(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockEngine)(nil).Query), varargs...)
}

// Restore mocks base method.
func (m *MockEngine) Restore(ctx context.Context, filter ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range filter {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Restore", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockEngineMockRecorder) Restore(ctx interface{}, filter ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, filter...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockEngine)(nil).Restore), varargs...)
}

// RightJoin mocks base method.
func (m *MockEngine) RightJoin(table, condition string) sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RightJoin", table, condition)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// RightJoin indicates an expected call of RightJoin.
func (mr *MockEngineMockRecorder) RightJoin(table, condition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RightJoin", reflect.TypeOf((*MockEngine)(nil).RightJoin), table, condition)
}

// Rollback mocks base method.
func (m *MockEngine) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockEngineMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockEngine)(nil).Rollback))
}

// ShowSQL mocks base method.
func (m *MockEngine) ShowSQL(showSQL bool) sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowSQL", showSQL)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// ShowSQL indicates an expected call of ShowSQL.
func (mr *MockEngineMockRecorder) ShowSQL(showSQL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowSQL", reflect.TypeOf((*MockEngine)(nil).ShowSQL), showSQL)
}

// Sum mocks base method.
func (m *MockEngine) Sum(col string, alias ...string) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{col}
	for _, a := range alias {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Sum", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Sum indicates an expected call of Sum.
func (mr *MockEngineMockRecorder) Sum(col interface{}, alias ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{col}, alias...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sum", reflect.TypeOf((*MockEngine)(nil).Sum), varargs...)
}

// Sync mocks base method.
func (m *MockEngine) Sync(ctx context.Context, tables ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range tables {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Sync", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockEngineMockRecorder) Sync(ctx interface{}, tables ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, tables...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockEngine)(nil).Sync), varargs...)
}

// Table mocks base method.
func (m *MockEngine) Table(name string) sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Table", name)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Table indicates an expected call of Table.
func (mr *MockEngineMockRecorder) Table(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Table", reflect.TypeOf((*MockEngine)(nil).Table), name)
}

// UpdateOne mocks base method.
func (m *MockEngine) UpdateOne(ctx context.Context, document any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOne", ctx, document)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockEngineMockRecorder) UpdateOne(ctx, document interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockEngine)(nil).UpdateOne), ctx, document)
}

// Where mocks base method.
func (m *MockEngine) Where(cond string, args ...any) sql0.Engine {
	m.ctrl.T.Helper()
	varargs := []interface{}{cond}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Where", varargs...)
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// Where indicates an expected call of Where.
func (mr *MockEngineMockRecorder) Where(cond interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{cond}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Where", reflect.TypeOf((*MockEngine)(nil).Where), varargs...)
}

// WithDeleted mocks base method.
func (m *MockEngine) WithDeleted() sql0.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithDeleted")
	ret0, _ := ret[0].(sql0.Engine)
	return ret0
}

// WithDeleted indicates an expected call of WithDeleted.
func (mr *MockEngineMockRecorder) WithDeleted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithDeleted", reflect.TypeOf((*MockEngine)(nil).WithDeleted))
}
